version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u sjega93 -p Ruby240895!
  build:
    dockerfile: ./Dockerfile
    commands:
      - docker-compose build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push sjega93:latest