version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=shoot
      - MYSQL_DATABASE=springbootemployee
      - MYSQL_USER=sjega93
      - MYSQL_PASSWORD=abc
    ports:
      - '3303:3303'
  app:
    depends_on:
      - mariadb
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    stdin_open: true
    tty: true


