version: "3.8"
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mysqldb
    restart: unless-stopped
    environment:
       MYSQL_DATABASE: springbootemployee
       MYSQL_USER: shoot
       MYSQL_PASSWORD: shoot
    networks:
      - app
    ports:
      - '127.0.0.1:3306:3306'
  app:
    depends_on:
      - mariadb
    build: 
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app
    stdin_open: true
    tty: true
networks:
   app:
      driver: bridge

