version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=shoot
      - MYSQL_DATABASE=springbootemployee
      - MYSQL_USER=sjega93
      - MYSQL_PASSWORD=abc
    ports:
      - '3306:3306'
  app:
    depends_on:
      - mariadb
    command: sh -c './wait-for mysqldb:3306 -- npm start'
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    links:
      - mariadb:appdb
    stdin_open: true
    tty: true


