version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=springbootemployee
      - MARIADB_USER=root
    networks:
      - app
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mariadb
    build: 
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mysqldb:3306/?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    networks:
      - app
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
networks:
   app:
      driver: bridge
volumes:
  db:
