version: "3.8"
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mysqldb
    restart: unless-stopped
    environment:
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: springbootemployee
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: root
    networks:
      - app
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mariadb
    build: 
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
networks:
   app:
      driver: bridge
volumes:
  db:
